### LLamaar al home
GET http://localhost:3000/

### Recuperar todas las películas
GET http://localhost:3000/movies

### Recuperar una película
GET http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Recuperar todas las peliculas por un género
GET http://localhost:3000/movies?genre=sci-fi

### Crear una película con POST
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "Oppenheiimer",
    "year": 100,
    "director": "Christopher Nolan",
    "duration": 180.4,
    "poster": "https://m.media-amazon.com/images/I/81XXxWVKbOL._SL1500_.jpg",
    "genre": [
        "Sci-fi",
        "Drama"
    ]
}

### Actualizar una película
PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "director": "Nathan Hidalgo"
}

### Eliminar una película
DELETE http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3